# Generated by Django 5.1.1 on 2025-09-18 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_academicperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='academics.educationlevel')),
            ],
            options={
                'ordering': ['level__name', 'order', 'name'],
                'indexes': [models.Index(fields=['level', 'order'], name='academics_g_level_i_a4a605_idx')],
                'unique_together': {('level', 'name')},
            },
        ),
    ]
