# Generated by Django 5.1.1 on 2025-09-18 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('capacity', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='academics.grade')),
            ],
            options={
                'ordering': ['grade__level__name', 'grade__order', 'grade__name', 'name'],
                'indexes': [models.Index(fields=['grade', 'name'], name='academics_s_grade_i_8e9ef9_idx')],
                'unique_together': {('grade', 'name')},
            },
        ),
    ]
