# Generated by Django 5.1.1 on 2025-09-18 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('short_name', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academics.educationlevel')),
            ],
            options={
                'ordering': ['level__name', 'name'],
                'indexes': [models.Index(fields=['level', 'name'], name='academics_s_level_i_a9c222_idx')],
                'unique_together': {('level', 'name')},
            },
        ),
    ]
